### ISSUE TITLE
Confusion regarding EMPTY_MIDDLEWARE

### ISSUE THREAD

**Issue by tdreyno** [mitchellh/middleware#2]
Hi, I'm a little confused about how `EMPTY_MIDDLEWARE` works. It's empty and therefore returns `nil`. Since it runs last, it makes all of my stacks return `nil` instead of their current `env`.

I'm doing the following in my code to work around this:

```
::Middleware::Runner.const_set :EMPTY_MIDDLEWARE, lambda { |env| env }
```

Am I misunderstanding something? Doing the whole stack backwards?

**Comment by SebastianEdwards** [comment]
I'm also a little confused about this. Would be great to get some clarification on this issue. Is this by design or an oversight?

**Comment by mitchellh** [comment]
Ah, I can see the confusion here. When I have used middleware, I always used `env` as a mutable hash, so I never inspected the return value of the middlewares. However, I can see value in doing so...

I'll merge PR #3.

**Comment by SebastianEdwards** [comment]
Awesome; I am working on a gem which uses the middleware env in this way so it would be great to see this change up on the rubygems source.

Thanks so much for this gem; it's a much better implementation than anything I'd have rolled myself.

**Comment by ramontayag** [comment]
[PR#3](https://github.com/mitchellh/middleware/pull/3) does not seem like it has been merged, yet? :)

**Comment by lulalala** [comment]
I want to bump this since #3 has not been merged.

Also it would be great if the doc can explain what the implementation should look like for the end stack. End stack (e.g. Rails in Rack app) are technically not a middleware, but will be implemented as one here. What should it return? Should it call `@app`?
